name: .NET Core Desktop
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
  
    steps:

    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'
   
    - run: dotnet publish In-Anh/In-Anh.sln -c Release --force --no-restore --output publishCode
