name: My .NET Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd

    steps:
    - name: Stop example.com
      run: appcmd stop sites "jinnie.shop"
    
    - name: Start example.com
      run: appcmd start sites "jinnie.shop"

    - uses: actions/checkout@v3

  
    
