name: .NET Core Desktop
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted, self-hosted]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3.1.0
      - run: |
          NET STOP WAS /Y 
          dotnet publish In-Anh/In-Anh.sln -c Release --force --output publishCode
          NET START W3SVC
