name: .NET Core Desktop
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: iisreset /stop
    steps:
    - run: powersell stop sites "jinnie.shop" -RunAsAdmin
    
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'
    - run: dotnet build In-Anh
    - run: dotnet publish In-Anh
    - run: iisreset /noforce
    
