name: .NET Core Desktop
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [self-hosted, self-hosted]
  
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'
  
    - run: |
             
             stop-iissite -Name jinnie.shop -Confirm: $false
             Start-Sleep -s 5
             dotnet publish In-Anh/In-Anh.sln -c Release --force --output publishCode
             start-webapppool jinnie.shop
             start-iissite jinnie.shop 
